#!/usr/bin/env bash

json_value() {
  echo "$1" | while read k v; do [[ $k =~ "\"$2\"" ]] && v=${v##\"} && echo ${v%%\"*}; done
}

dock_release() {
  if [[ $# -ne 1 ]]; then
    echo "usage: dock release <owner/repo>"
  else
    release=$(curl -sSL "https://api.github.com/repos/$2/releases?per_page=1")
    name=$(json_value "$release" 'name') 
    tarball_url=$(json_value "$release" 'tarball_url')
    image_name="$1:$name"

    echo $image_name
  fi
}

try_pull() {
  repo_dir="${4:-.}/$3"
  release_dir="$repo_dir/$1"

  if [[ ! -d "$release_dir" ]]; then
    mkdir -p "$release_dir"
    curl -sSL $2 | tar xzp --strip-components=1 -C "$release_dir"
    (cd "$release_dir" && docker build -t $image_name .)
  fi
}

dock_pull() {
  if [[ $# -lt 1 ]]; then
    echo "usage: dock pull <owner/repo> [workspace]"
  else
    dock_release "$1"
    try_pull $name $tarball_url $@
  fi
}

case "$1" in

release)
  shift
  dock_release $@
;;

pull)
  shift
  dock_pull $@
;;

*)
;;

esac
