#!/usr/bin/env bash

json_value() {
  echo "$1" | while read k v; do [[ $k =~ "\"$2\"" ]] && v=${v##\"} && echo ${v%%\"*}; done
}

dock_release() {
  if [[ $# -ne 1 ]]; then
    echo "usage: dock release <owner/repo>"
  else
    release=$(curl -sSL "https://api.github.com/repos/$2/releases?per_page=1")
    name=$(json_value "$release" 'name') 
    tarball_url=$(json_value "$release" 'tarball_url') 

    echo $name $tarball_url
  fi
}

try_pull() {
  release_dir="${3:-.}/$1"

  if [[ ! -d "$release_dir" ]]; then
    mkdir -p "$release_dir"
    curl -sSL $2 | tar xzp -C "$release_dir"
  fi
}

dock_pull() {
  if [[ $# -lt 1 ]]; then
    echo "usage: dock pull <owner/repo> [workspace]"
  else
    dock_release "$1"
    try_pull $name $tarball_url $2
  fi
}

case "$1" in

release)
  shift
  dock_release $@
;;

pull)
  shift
  dock_pull $@
;;

*)
;;

esac
